# Generated by Django 5.1.6 on 2025-02-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_iscrizione', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('fascia_oraria', models.CharField(max_length=50)),
                ('formato', models.CharField(choices=[('DRAFT', 'Draft'), ('ARAM', 'ARAM')], default='DRAFT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_evento', models.DateField()),
                ('durata_minuti', models.IntegerField(blank=True, null=True)),
                ('draghi_rossa', models.IntegerField(default=0)),
                ('draghi_blu', models.IntegerField(default=0)),
                ('anima_drago_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('drago_anziano_rossa', models.IntegerField(blank=True, null=True)),
                ('drago_anziano_blu', models.IntegerField(blank=True, null=True)),
                ('baroni_rossa', models.IntegerField(default=0)),
                ('baroni_blu', models.IntegerField(default=0)),
                ('araldo_rossa', models.IntegerField(default=0)),
                ('araldo_blu', models.IntegerField(default=0)),
                ('atakhan_side', models.CharField(blank=True, max_length=50, null=True)),
                ('modalita', models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], default='BO1', max_length=3)),
                ('fase_torneo', models.CharField(choices=[('Gruppi', 'Gruppi'), ('Quarti', 'Quarti'), ('Semifinale', 'Semifinale'), ('Finale', 'Finale')], default='Gruppi', max_length=15)),
                ('numero_partita_nella_serie', models.IntegerField(default=1)),
                ('serie_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serie_partite', to='backend.partita')),
                ('anima_drago_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anima_drago', to='backend.squadra')),
                ('atakhan_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atakhan_preso', to='backend.squadra')),
                ('squadra_blu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_blu', to='backend.squadra')),
                ('squadra_rossa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_rosse', to='backend.squadra')),
                ('vincitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_vinte', to='backend.squadra')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='backend.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='NotaPartita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('testo', models.TextField()),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='backend.partita')),
            ],
        ),
        migrations.CreateModel(
            name='PickBanPartita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campione', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('pick', 'Pick'), ('ban', 'Ban')], max_length=4)),
                ('ordine', models.IntegerField()),
                ('ruolo', models.CharField(blank=True, max_length=50, null=True)),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickban', to='backend.partita')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickban_squadra', to='backend.squadra')),
            ],
        ),
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_iscrizione', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocatori', to='backend.squadra')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticheGiocatorePartita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campione_usato', models.CharField(max_length=50)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('danni_totali_campioni', models.IntegerField(default=0)),
                ('danni_presi_totali', models.IntegerField(default=0)),
                ('cure_totali', models.IntegerField(default=0)),
                ('oro_totale', models.IntegerField(default=0)),
                ('torri_distrutte', models.IntegerField(default=0)),
                ('inibitori_distrutti', models.IntegerField(default=0)),
                ('danni_obbiettivi', models.IntegerField(default=0)),
                ('minion_kill', models.IntegerField(default=0)),
                ('mostri_uccisi', models.IntegerField(default=0)),
                ('wards_piazzate', models.IntegerField(default=0)),
                ('wards_distrutte', models.IntegerField(default=0)),
                ('punteggio_visione', models.IntegerField(default=0)),
                ('primo_sangue', models.BooleanField(default=False)),
                ('serie_piu_lunga', models.IntegerField(default=0)),
                ('maggiore_uccisione_multipla', models.IntegerField(default=0)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiche', to='backend.giocatore')),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiche_giocatori', to='backend.partita')),
            ],
        ),
    ]
