# Generated by Django 5.1.6 on 2025-02-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
                ('quota_iscrizione', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.squadra')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.torneo')),
            ],
        ),
    ]
