# Generated by Django 5.1.6 on 2025-02-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_iscrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='partita',
            name='anima_drago_tipo',
            field=models.CharField(blank=True, choices=[('INFERNALE', 'INFERNALE'), ('MONTAGNA', 'MONTAGNA'), ('OCEANO', 'OCEANO'), ('ARIA', 'ARIA'), ('HEXTECH', 'HEXTECH'), ('CHEMTANK', 'CHEMTANK')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partita',
            name='atakhan_side',
            field=models.CharField(blank=True, choices=[('BOT', 'BOT'), ('TOP', 'TOP')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partita',
            name='drago_anziano_blu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partita',
            name='drago_anziano_rossa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partita',
            name='durata_minuti',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pickbanpartita',
            name='campione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.campione'),
        ),
    ]
