# Generated by Django 5.1.6 on 2025-02-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pickbanpartita_ruolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp', to='backend.giocatore'),
        ),
    ]
