# Generated by Django 5.1.6 on 2025-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_partita_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='durata_minuti',
            field=models.IntegerField(null=True),
        ),
    ]
