# Generated by Django 5.1.6 on 2025-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_partita_durata_minuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='durata_minuti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
