# Generated by Django 5.1.6 on 2025-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_partita_conclusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadra',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
