# Generated by Django 5.1.6 on 2025-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_squadra_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campione',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='campioni/'),
        ),
    ]
