# Generated by Django 5.1.6 on 2025-03-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_campione_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadra',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squadra',
            name='livello',
            field=models.IntegerField(default=1),
        ),
    ]
