# Generated by Django 5.1.6 on 2025-03-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_squadra_exp_squadra_livello'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi', to='backend.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='partita',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_fase', to='backend.fasetorneo'),
        ),
        migrations.CreateModel(
            name='Girone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gironi', to='backend.fasetorneo')),
            ],
        ),
        migrations.AddField(
            model_name='partita',
            name='girone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_girone', to='backend.girone'),
        ),
    ]
