# Generated by Django 5.1.6 on 2025-03-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_fasetorneo_partita_fase_girone_partita_girone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='fase_torneo',
        ),
    ]
