# Generated by Django 5.1.6 on 2025-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_classificatorneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='fascia_oraria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
