# Generated by Django 5.1.6 on 2025-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_torneo_fascia_oraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetorneo',
            name='tipologia',
            field=models.CharField(choices=[('GRUPPI', 'Gironi'), ('ELIMINAZIONE_DIRETTA', 'Eliminazione diretta'), ('DOPPIA_ELIMINAZIONE', 'Doppia eliminazione'), ('ROUND_ROBIN', 'Round Robin'), ('KING_OF_THE_HILL', 'King of the Hill'), ('CAMPIONATO', 'Campionato a punti'), ('ALTRO', 'Altro')], default='ALTRO', max_length=30),
        ),
    ]
