# Generated by Django 5.1.6 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_fasetorneo_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='round_num',
            field=models.IntegerField(default=1),
        ),
    ]
