# Generated by Django 5.1.6 on 2025-04-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_partita_round_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='squadra_blu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_blu', to='backend.squadra'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='squadra_rossa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_rosse', to='backend.squadra'),
        ),
    ]
