# Generated by Django 5.1.6 on 2025-04-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_partita_squadra_blu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='bracket_confermato',
            field=models.BooleanField(default=False),
        ),
    ]
