# Generated by Django 5.1.6 on 2025-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_partita_bracket_confermato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='bracket_confermato',
        ),
        migrations.AddField(
            model_name='girone',
            name='bracket_confermato',
            field=models.BooleanField(default=False),
        ),
    ]
