# Generated by Django 5.1.6 on 2025-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_partita_bracket_confermato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girone',
            name='bracket_confermato',
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='bracket_confermato',
            field=models.BooleanField(default=False),
        ),
    ]
