from .torneo import Torneo
from .squadra import Squadra
from .giocatore import Giocatore
from .partita import Partita
from .pickban import PickBanPartita
from .nota_partita import NotaPartita
from .statistiche_giocatore_partita import StatisticheGiocatorePartita
from .iscrizione import Iscrizione
from .campione import Campione