name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4

      - name: Verify Docker`n        shell: powershell`n        run: |`n          docker context ls`n          docker context use default`n          docker version

      - name: Deploy
        shell: powershell
        run: |
          cd $env:GITHUB_WORKSPACE
          docker compose up -d --build
          docker compose ps

